### ISSUE TITLE
docker process not writing out .aws/credentials

### ISSUE THREAD

**Issue by aneal** [turnerlabs/samlkeygen#19]
When running 1.3.0 in docker the $HOME/.aws/credentials file is empty

`samld` (this is the following alias):  `alias samld='docker run -it -v ~/.aws:/aws turnerlabs/samlkeygen authenticate --url https://sts.turner.com/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices --domain Turner --username $USER --all-accounts'`
```Turner\aneal's password:
Writing credentials for profile aws-brandcentral-prod:aws-brandcentral-prod-admin
Writing credentials for profile aws-mediaenablement:aws-mediaenablement-admin
Writing credentials for profile aws-adultswim:aws-adultswim-admin
...
```
`ls -l ~/.aws/credentials`
    -rw-r--r--  1 aneal  staff      0 Dec 12 10:56 credentials

**Comment by mjreed-wbd** [comment]
Fixed in 1.3.1.
