### ISSUE TITLE
Unable to overwrite existing credentials file

### ISSUE THREAD

**Issue by RobCannon** [turnerlabs/samlkeygen#20]
When a credentials file already exists, running samld 1.3 under Windows will return this error:

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\rcannon/.aws\\credentials.tmp' -> 'C:\\Users\\rcannon/.aws\
\credentials'

**Comment by mjreed-wbd** [comment]
This is addressed by PR #22.
